#
# removed "ext-pdo_pgsql": "*", from composer
#
version: "3"
services:
  app:
    tty: true
    build:
      context: .
      dockerfile: docker/Dockerfile
      args:
        app_path: 
    env_file:
      - docker/.env
    ports:
      - "9000:9000"
    volumes:
      - ${PWD}:/var/www/html
      # - ${PWD}/docker/conf/php.ini:/opt/bitnami/php/lib/php.ini
    links:
      - db
      - rabbit

  nginx:
    image: 'nginx:alpine'
    depends_on:
      - app
    ports:
      - '8081:80'
      #- '443:443'
    volumes:
      - ${PWD}/docker/conf/spryker-suite.conf:/etc/nginx/conf.d/default.conf

  db:
    image: postgres:alpine
    volumes:
      - $PWD/data/postgresql:/var/lib/postgresql:rw

  jenkins:
    image: jenkins:alpine

  redis:
    image: redis:alpine

  rabbit:
    image: rabbitmq:alpine
