version: "3.4"

x-spryker_common: &spryker_common
  tty: true
  env_file:
    - ${PWD}/docker/.env
  volumes:
    - ${PWD}:/app
    # - ${PWD}/docker/conf/php.ini:/opt/bitnami/php/lib/php.ini
  links:
    - db
    - rabbit
    - elasticsearch

services:
  app:
    <<: *spryker_common
    build:
      context: .
      dockerfile: docker/Dockerfile
    volumes:
      - ${PWD}:/app
      - ${PWD}/public/Zed:/var/www/html
    ports:
      - "9000:9000"
  yves:
    <<: *spryker_common
    image: suite_app:latest
    volumes:
      - ${PWD}:/app
      - ${PWD}/public/Yves:/var/www/html
    ports:
      - "9001:9000"
  glue:
    <<: *spryker_common
    image: suite_app:latest
    volumes:
      - ${PWD}:/app
      - ${PWD}/public/Glue:/var/www/html
    ports:
      - "9002:9000"

  nginx:
    image: 'nginx:alpine'
    depends_on:
      - app
    ports:
      - '8000:8000'
      - '8001:8001'
      - '8002:8002'
      #- '443:443'
    expose:
      - 8000
      - 8001
      - 8002
    volumes:
      - ${PWD}/docker/conf/spryker-suite.conf:/etc/nginx/conf.d/default.conf

  db:
    image: postgres:alpine
    ports:
      - "5433:5432"
    volumes:
      - $PWD/data/postgresql:/var/lib/postgresql:rw

  jenkins:
    image: jenkins:alpine

  redis:
    image: redis:alpine

  rabbit:
    image: rabbitmq:3.6-management-alpine
    ports:
      - "15672:15672"

  elasticsearch:
    image: elasticsearch:5-alpine
    ports:
      - "9200:9200"
      - "9300:9300"