version: "3.4"

x-spryker_common: &spryker_common
  tty: true
  env_file:
    - ${PWD}/docker/.env
  links:
    - db
    - redis
    - rabbit
    - elasticsearch

services:
  zed:
    <<: *spryker_common
    build:
      context: .
      dockerfile: docker/Dockerfile
    volumes:
      - ${PWD}/config:/var/www/html/config
      - ${PWD}/public:/var/www/html/public
    ports:
      - "9000:9000"

  yves:
    <<: *spryker_common
    image: suite_app:latest
    # volumes:
    #   - ${PWD}:/var/www/html:delegated
    volumes:
      - ${PWD}/config:/var/www/html/config
      - ${PWD}/public:/var/www/html/public
    ports:
      - "9001:9000"

  glue:
    <<: *spryker_common
    image: suite_app:latest
    # volumes:
    #   - ${PWD}:/var/www/html:delegated
    ports:
      - "9002:9000"

  nginx:
    image: 'nginx:alpine'
    depends_on:
      - zed
    ports:
      - '80:80'
    volumes:
      - ${PWD}/docker/conf/spryker-suite.conf:/etc/nginx/conf.d/default.conf
      - ${PWD}/public/Zed/assets:/var/www/html/public/Zed/assets
      - ${PWD}/public/Yves/assets:/var/www/html/public/Yves/assets

  db:
    image: postgres:alpine
    ports:
      - "5433:5432"
    volumes:
      - $PWD/data/postgresql:/var/lib/postgresql:rw

  jenkins:
    image: jenkins:alpine
    ports:
      - "8080:8080"

  redis:
    image: redis:alpine

  rabbit:
    image: rabbitmq:3.6.15-management-alpine
    ports:
      - "15672:15672"

  elasticsearch:
    image: elasticsearch:5-alpine
    ports:
      - "9200:9200"
      - "9300:9300"